### ISSUE TITLE
Remover el required de members y bosses en offices y sections

### ISSUE THREAD

**Issue by adminAgenciaServitec** [AgenciaServitec/korekenke#170]

**Comment by Ignacio2906** [comment]
Ofices


![image](https://github.com/AgenciaServitec/korekenke/assets/145935490/ecc5cdf1-4f61-4210-8964-2b8a6e7b5222)
![image](https://github.com/AgenciaServitec/korekenke/assets/145935490/e5e4b060-1983-4b16-a50d-106a841eb5c3)

**Comment by Ignacio2906** [comment]
Section

![image](https://github.com/AgenciaServitec/korekenke/assets/145935490/d930213d-0c07-46f9-a51b-842edd0a0543)
![image](https://github.com/AgenciaServitec/korekenke/assets/145935490/6c2fb04e-8e26-454f-b7ea-19420b0a76ac)
