### ISSUE TITLE
Create new roles

### ISSUE THREAD

**Issue by adminAgenciaServitec** [AgenciaServitec/korekenke#57]
## Crear todos los roles en la nueva aplicacion

https://korekenke.mil.pe/site/login/926730944

<img width="1434" alt="Screenshot 2024-05-07 at 11 47 53 AM" src="https://github.com/AgenciaServitec/korekenke/assets/104750139/989d2e12-58f4-4d33-baa3-cf1c9e79f1e7">

## NO OLVIDAR LOS ROLES MAS IMPORTANTES:
![Screenshot 2024-05-13 at 3 55 47 PM](https://github.com/AgenciaServitec/korekenke/assets/104750139/b1ab1112-5337-4d70-b7af-61167aa32a36)

**Comment by Ignacio2906** [comment]
![image](https://github.com/AgenciaServitec/korekenke/assets/145935490/93fa20b6-0c92-46ec-ba90-6ce174b5bc24)


![image](https://github.com/AgenciaServitec/korekenke/assets/145935490/d12adfd7-0e73-4718-a7e8-98a633e62885)


![image](https://github.com/AgenciaServitec/korekenke/assets/145935490/4a09d75c-4064-426f-93a9-be5854bb3d8d)


![image](https://github.com/AgenciaServitec/korekenke/assets/145935490/72177d52-1b1d-4a4a-ac06-7eb2fc5f0d98)


![image](https://github.com/AgenciaServitec/korekenke/assets/145935490/a8214b8a-46cc-4762-8942-e2a8488c9b98)


![image](https://github.com/AgenciaServitec/korekenke/assets/145935490/f7055108-b588-46f0-a9f3-a5fab58f3fab)
